/**
 * COMPREHENSIVE NORMAL RANGES DATABASE
 * Uganda Population-Specific Reference Ranges
 * 
 * This file contains pre-configured normal ranges for all laboratory tests
 * with support for gender-specific, age-specific, and critical thresholds.
 */

import { TestNormalRange } from '@/types';

export interface NormalRangeConfig {
  testCode: string;
  testName: string;
  parameters: Omit<TestNormalRange, 'id' | 'testId' | 'createdAt' | 'updatedAt'>[];
}

/**
 * HEMATOLOGY NORMAL RANGES
 */
export const HEMATOLOGY_RANGES: NormalRangeConfig[] = [
  {
    testCode: 'FBC',
    testName: 'Full Hemogram',
    parameters: [
      {
        parameter: 'Hemoglobin',
        unit: 'g/dL',
        rangeType: 'numeric',
        normalRangeMale: '13.0-17.0',
        normalRangeFemale: '12.0-15.0',
        normalMinMale: 13.0,
        normalMaxMale: 17.0,
        normalMinFemale: 12.0,
        normalMaxFemale: 15.0,
        criticalLowMale: 7.0,
        criticalHighMale: 20.0,
        criticalLowFemale: 7.0,
        criticalHighFemale: 18.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'WBC Count',
        unit: 'cells/μL',
        rangeType: 'numeric',
        normalRangeGeneral: '4,000-11,000',
        normalMinGeneral: 4000,
        normalMaxGeneral: 11000,
        criticalLowGeneral: 2000,
        criticalHighGeneral: 30000,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'RBC Count',
        unit: 'million/μL',
        rangeType: 'numeric',
        normalRangeMale: '4.5-5.5',
        normalRangeFemale: '4.0-5.0',
        normalMinMale: 4.5,
        normalMaxMale: 5.5,
        normalMinFemale: 4.0,
        normalMaxFemale: 5.0,
        criticalLowGeneral: 2.5,
        criticalHighGeneral: 7.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Platelet Count',
        unit: 'cells/μL',
        rangeType: 'numeric',
        normalRangeGeneral: '150,000-450,000',
        normalMinGeneral: 150000,
        normalMaxGeneral: 450000,
        criticalLowGeneral: 50000,
        criticalHighGeneral: 1000000,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Hematocrit',
        unit: '%',
        rangeType: 'numeric',
        normalRangeMale: '40-54',
        normalRangeFemale: '36-48',
        normalMinMale: 40,
        normalMaxMale: 54,
        normalMinFemale: 36,
        normalMaxFemale: 48,
        criticalLowGeneral: 20,
        criticalHighGeneral: 65,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'MCV',
        unit: 'fL',
        rangeType: 'numeric',
        normalRangeGeneral: '80-100',
        normalMinGeneral: 80,
        normalMaxGeneral: 100,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'MCH',
        unit: 'pg',
        rangeType: 'numeric',
        normalRangeGeneral: '27-33',
        normalMinGeneral: 27,
        normalMaxGeneral: 33,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'MCHC',
        unit: 'g/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '32-36',
        normalMinGeneral: 32,
        normalMaxGeneral: 36,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'MP',
    testName: 'Malaria Parasite Test',
    parameters: [
      {
        parameter: 'Malaria Parasite',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Negative',
        normalValue: 'Negative',
        abnormalValues: ['Positive', '+', '++', '+++', '++++'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'BGRH',
    testName: 'Blood Group & Rh Factor',
    parameters: [
      {
        parameter: 'Blood Group',
        unit: '',
        rangeType: 'category',
        normalRangeGeneral: 'A/B/AB/O',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Rh Factor',
        unit: '',
        rangeType: 'category',
        normalRangeGeneral: 'Positive/Negative',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'ESR',
    testName: 'ESR (Erythrocyte Sedimentation Rate)',
    parameters: [
      {
        parameter: 'ESR',
        unit: 'mm/hr',
        rangeType: 'numeric',
        normalRangeMale: '0-15',
        normalRangeFemale: '0-20',
        normalMinMale: 0,
        normalMaxMale: 15,
        normalMinFemale: 0,
        normalMaxFemale: 20,
        criticalHighGeneral: 100,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'RETIC',
    testName: 'Reticulocyte Count',
    parameters: [
      {
        parameter: 'Reticulocyte Count',
        unit: '%',
        rangeType: 'numeric',
        normalRangeGeneral: '0.5-2.5',
        normalMinGeneral: 0.5,
        normalMaxGeneral: 2.5,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
];

/**
 * BIOCHEMISTRY NORMAL RANGES
 */
export const BIOCHEMISTRY_RANGES: NormalRangeConfig[] = [
  {
    testCode: 'LFT',
    testName: 'Liver Function Tests',
    parameters: [
      {
        parameter: 'Total Bilirubin',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '0.1-1.2',
        normalMinGeneral: 0.1,
        normalMaxGeneral: 1.2,
        criticalHighGeneral: 12.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Direct Bilirubin',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '0.0-0.3',
        normalMinGeneral: 0.0,
        normalMaxGeneral: 0.3,
        criticalHighGeneral: 5.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'AST (SGOT)',
        unit: 'U/L',
        rangeType: 'numeric',
        normalRangeGeneral: '5-40',
        normalMinGeneral: 5,
        normalMaxGeneral: 40,
        criticalHighGeneral: 500,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'ALT (SGPT)',
        unit: 'U/L',
        rangeType: 'numeric',
        normalRangeGeneral: '7-56',
        normalMinGeneral: 7,
        normalMaxGeneral: 56,
        criticalHighGeneral: 500,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'ALP',
        unit: 'U/L',
        rangeType: 'numeric',
        normalRangeGeneral: '44-147',
        normalMinGeneral: 44,
        normalMaxGeneral: 147,
        criticalHighGeneral: 500,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Total Protein',
        unit: 'g/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '6.0-8.3',
        normalMinGeneral: 6.0,
        normalMaxGeneral: 8.3,
        criticalLowGeneral: 4.0,
        criticalHighGeneral: 10.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Albumin',
        unit: 'g/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '3.5-5.5',
        normalMinGeneral: 3.5,
        normalMaxGeneral: 5.5,
        criticalLowGeneral: 2.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'RFT',
    testName: 'Renal Function Tests',
    parameters: [
      {
        parameter: 'Urea',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '7-20',
        normalMinGeneral: 7,
        normalMaxGeneral: 20,
        criticalLowGeneral: 2,
        criticalHighGeneral: 100,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Creatinine',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeMale: '0.7-1.3',
        normalRangeFemale: '0.6-1.1',
        normalMinMale: 0.7,
        normalMaxMale: 1.3,
        normalMinFemale: 0.6,
        normalMaxFemale: 1.1,
        criticalHighGeneral: 10.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'eGFR',
        unit: 'mL/min/1.73m²',
        rangeType: 'numeric',
        normalRangeGeneral: '90-120',
        normalMinGeneral: 90,
        normalMaxGeneral: 120,
        criticalLowGeneral: 15,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Uric Acid',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeMale: '3.5-7.2',
        normalRangeFemale: '2.6-6.0',
        normalMinMale: 3.5,
        normalMaxMale: 7.2,
        normalMinFemale: 2.6,
        normalMaxFemale: 6.0,
        criticalHighGeneral: 12.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Sodium',
        unit: 'mmol/L',
        rangeType: 'numeric',
        normalRangeGeneral: '136-145',
        normalMinGeneral: 136,
        normalMaxGeneral: 145,
        criticalLowGeneral: 120,
        criticalHighGeneral: 160,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Potassium',
        unit: 'mmol/L',
        rangeType: 'numeric',
        normalRangeGeneral: '3.5-5.1',
        normalMinGeneral: 3.5,
        normalMaxGeneral: 5.1,
        criticalLowGeneral: 2.5,
        criticalHighGeneral: 6.5,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Chloride',
        unit: 'mmol/L',
        rangeType: 'numeric',
        normalRangeGeneral: '98-107',
        normalMinGeneral: 98,
        normalMaxGeneral: 107,
        criticalLowGeneral: 80,
        criticalHighGeneral: 115,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'GLUC',
    testName: 'Blood Glucose',
    parameters: [
      {
        parameter: 'Glucose (Fasting)',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '70-100',
        normalMinGeneral: 70,
        normalMaxGeneral: 100,
        criticalLowGeneral: 40,
        criticalHighGeneral: 400,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Glucose (Random)',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '70-140',
        normalMinGeneral: 70,
        normalMaxGeneral: 140,
        criticalLowGeneral: 40,
        criticalHighGeneral: 400,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'LIPID',
    testName: 'Lipid Profile',
    parameters: [
      {
        parameter: 'Total Cholesterol',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '<200',
        normalMinGeneral: 100,
        normalMaxGeneral: 200,
        criticalHighGeneral: 300,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'HDL Cholesterol',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '>40',
        normalMinGeneral: 40,
        normalMaxGeneral: 100,
        criticalLowGeneral: 20,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'LDL Cholesterol',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '<100',
        normalMinGeneral: 50,
        normalMaxGeneral: 100,
        criticalHighGeneral: 190,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Triglycerides',
        unit: 'mg/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '<150',
        normalMinGeneral: 50,
        normalMaxGeneral: 150,
        criticalHighGeneral: 500,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'HBA1C',
    testName: 'HbA1c (Glycated Hemoglobin)',
    parameters: [
      {
        parameter: 'HbA1c',
        unit: '%',
        rangeType: 'numeric',
        normalRangeGeneral: '4.0-5.6',
        normalMinGeneral: 4.0,
        normalMaxGeneral: 5.6,
        criticalHighGeneral: 12.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
];

/**
 * SEROLOGY NORMAL RANGES
 */
export const SEROLOGY_RANGES: NormalRangeConfig[] = [
  {
    testCode: 'HIV',
    testName: 'HIV Rapid Test',
    parameters: [
      {
        parameter: 'HIV Test',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Non-Reactive',
        normalValue: 'Non-Reactive',
        abnormalValues: ['Reactive', 'Positive'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'HBSAG',
    testName: 'Hepatitis B Surface Antigen',
    parameters: [
      {
        parameter: 'HBsAg',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Negative',
        normalValue: 'Negative',
        abnormalValues: ['Positive', 'Reactive'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'HCV',
    testName: 'Hepatitis C Antibody',
    parameters: [
      {
        parameter: 'HCV Antibody',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Negative',
        normalValue: 'Negative',
        abnormalValues: ['Positive', 'Reactive'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'RPR',
    testName: 'Syphilis (RPR)',
    parameters: [
      {
        parameter: 'RPR',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Non-Reactive',
        normalValue: 'Non-Reactive',
        abnormalValues: ['Reactive', 'Positive'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'COVID',
    testName: 'COVID-19 Antigen Test',
    parameters: [
      {
        parameter: 'COVID-19 Antigen',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Negative',
        normalValue: 'Negative',
        abnormalValues: ['Positive', 'Detected'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
];

/**
 * MICROBIOLOGY NORMAL RANGES
 */
export const MICROBIOLOGY_RANGES: NormalRangeConfig[] = [
  {
    testCode: 'C&S',
    testName: 'Culture & Sensitivity',
    parameters: [
      {
        parameter: 'Culture Result',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'No Growth',
        normalValue: 'No Growth',
        abnormalValues: ['Growth', 'Positive'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Sensitivity',
        unit: '',
        rangeType: 'category',
        normalRangeGeneral: 'N/A',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'GXP',
    testName: 'TB GeneXpert',
    parameters: [
      {
        parameter: 'MTB Detection',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Not Detected',
        normalValue: 'Not Detected',
        abnormalValues: ['Detected', 'Positive'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Rifampicin Resistance',
        unit: '',
        rangeType: 'category',
        normalRangeGeneral: 'N/A',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'STOOL',
    testName: 'Stool Microscopy',
    parameters: [
      {
        parameter: 'Consistency',
        unit: '',
        rangeType: 'category',
        normalRangeGeneral: 'Formed',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Ova/Parasites',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'None Seen',
        normalValue: 'None Seen',
        abnormalValues: ['Seen', 'Present'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Pus Cells',
        unit: '/HPF',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Nil',
        normalValue: 'Nil',
        abnormalValues: ['Present', '+', '++', '+++'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'RBC',
        unit: '/HPF',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Nil',
        normalValue: 'Nil',
        abnormalValues: ['Present', '+', '++', '+++'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'URINE',
    testName: 'Urine Microscopy',
    parameters: [
      {
        parameter: 'Appearance',
        unit: '',
        rangeType: 'category',
        normalRangeGeneral: 'Clear',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'pH',
        unit: '',
        rangeType: 'numeric',
        normalRangeGeneral: '4.5-8.0',
        normalMinGeneral: 4.5,
        normalMaxGeneral: 8.0,
        ageGroup: 'All Ages',
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Protein',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Negative',
        normalValue: 'Negative',
        abnormalValues: ['Trace', '+', '++', '+++', '++++'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Glucose',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'Negative',
        normalValue: 'Negative',
        abnormalValues: ['Trace', '+', '++', '+++', '++++'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Pus Cells',
        unit: '/HPF',
        rangeType: 'numeric',
        normalRangeGeneral: '0-5',
        normalMinGeneral: 0,
        normalMaxGeneral: 5,
        criticalHighGeneral: 50,
        ageGroup: 'All Ages',
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'RBC',
        unit: '/HPF',
        rangeType: 'numeric',
        normalRangeGeneral: '0-3',
        normalMinGeneral: 0,
        normalMaxGeneral: 3,
        criticalHighGeneral: 30,
        ageGroup: 'All Ages',
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Epithelial Cells',
        unit: '/HPF',
        rangeType: 'category',
        normalRangeGeneral: 'Few',
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
      {
        parameter: 'Bacteria',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'None Seen',
        normalValue: 'None Seen',
        abnormalValues: ['Seen', '+', '++', '+++'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'GRAM',
    testName: 'Gram Stain',
    parameters: [
      {
        parameter: 'Gram Stain Result',
        unit: '',
        rangeType: 'qualitative',
        normalRangeGeneral: 'No Organisms Seen',
        normalValue: 'No Organisms Seen',
        abnormalValues: ['Organisms Seen', 'Gram Positive', 'Gram Negative'],
        ageGroup: 'All Ages',
        isEditable: false,
        isActive: true,
      },
    ],
  },
];

/**
 * HORMONE NORMAL RANGES
 */
export const HORMONE_RANGES: NormalRangeConfig[] = [
  {
    testCode: 'TFT',
    testName: 'Thyroid Function Tests',
    parameters: [
      {
        parameter: 'TSH',
        unit: 'mIU/L',
        rangeType: 'numeric',
        normalRangeGeneral: '0.4-4.0',
        normalMinGeneral: 0.4,
        normalMaxGeneral: 4.0,
        criticalLowGeneral: 0.1,
        criticalHighGeneral: 10.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Free T4',
        unit: 'ng/dL',
        rangeType: 'numeric',
        normalRangeGeneral: '0.8-1.8',
        normalMinGeneral: 0.8,
        normalMaxGeneral: 1.8,
        criticalLowGeneral: 0.3,
        criticalHighGeneral: 4.0,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
      {
        parameter: 'Free T3',
        unit: 'pg/mL',
        rangeType: 'numeric',
        normalRangeGeneral: '2.3-4.2',
        normalMinGeneral: 2.3,
        normalMaxGeneral: 4.2,
        ageGroup: 'Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'PSA',
    testName: 'PSA Total',
    parameters: [
      {
        parameter: 'PSA Total',
        unit: 'ng/mL',
        rangeType: 'numeric',
        normalRangeGeneral: '0.0-4.0',
        normalMinGeneral: 0.0,
        normalMaxGeneral: 4.0,
        criticalHighGeneral: 10.0,
        ageGroup: 'Adult Male',
        ageMin: 40,
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'BHCG',
    testName: 'Beta HCG (Pregnancy Test)',
    parameters: [
      {
        parameter: 'Beta HCG',
        unit: 'mIU/mL',
        rangeType: 'numeric',
        normalRangeGeneral: '<5 (Non-Pregnant)',
        normalMinGeneral: 0,
        normalMaxGeneral: 5,
        ageGroup: 'Female',
        isEditable: true,
        isActive: true,
      },
    ],
  },
  {
    testCode: 'PROG',
    testName: 'Progesterone',
    parameters: [
      {
        parameter: 'Progesterone',
        unit: 'ng/mL',
        rangeType: 'numeric',
        normalRangeFemale: '0.1-0.7 (Follicular), 2-25 (Luteal)',
        normalMinFemale: 0.1,
        normalMaxFemale: 25,
        ageGroup: 'Female Adult',
        ageMin: 18,
        isEditable: true,
        isActive: true,
      },
    ],
  },
];

/**
 * ALL NORMAL RANGES COMBINED
 */
export const ALL_NORMAL_RANGES: NormalRangeConfig[] = [
  ...HEMATOLOGY_RANGES,
  ...BIOCHEMISTRY_RANGES,
  ...SEROLOGY_RANGES,
  ...MICROBIOLOGY_RANGES,
  ...HORMONE_RANGES,
];

/**
 * Get normal ranges for a specific test code
 */
export function getNormalRangesForTest(testCode: string): NormalRangeConfig | undefined {
  return ALL_NORMAL_RANGES.find((range) => range.testCode === testCode);
}

/**
 * Get normal range for a specific parameter in a test
 */
export function getNormalRangeForParameter(
  testCode: string,
  parameterName: string
): Omit<TestNormalRange, 'id' | 'testId' | 'createdAt' | 'updatedAt'> | undefined {
  const testRange = getNormalRangesForTest(testCode);
  if (!testRange) return undefined;
  
  return testRange.parameters.find((param) => param.parameter === parameterName);
}
