// Facilities
export const FACILITIES = [
  {
    code: 'FLNT',
    name: 'FIRSTLINE MEDICAL LABORATORY DIAGNOSTICS - NTUNGAMO',
    address: 'Ntungamo District, Uganda',
    phone: '+256 700 000 001',
    email: 'ntungamo@firstlinelab.ug',
    licenseNumber: 'LAB-UG-2024-001',
  },
  {
    code: 'FLMB',
    name: 'FIRSTLINE MEDICAL LABORATORY DIAGNOSTICS - MBARARA',
    address: 'Mbarara District, Uganda',
    phone: '+256 700 000 002',
    email: 'mbarara@firstlinelab.ug',
    licenseNumber: 'LAB-UG-2024-002',
  },
  {
    code: 'PCMC',
    name: 'PRIMECURE MEDICAL CENTRE',
    address: 'Kampala, Uganda',
    phone: '+256 700 000 003',
    email: 'info@primecuremedical.ug',
    licenseNumber: 'LAB-UG-2024-003',
  },
];

// Test Categories and Tests
export const TEST_CATEGORIES = [
  {
    name: 'HEMATOLOGY',
    description: 'Blood tests and cell counts',
    tests: [
      {
        code: 'FBC',
        name: 'Full Hemogram',
        price: 15000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (EDTA)',
        containerType: 'Purple top tube',
        parameters: [
          { parameter: 'Hemoglobin', unit: 'g/dL', normalRangeMale: '13.0-17.0', normalRangeFemale: '12.0-15.0' },
          { parameter: 'WBC Count', unit: 'cells/μL', normalRangeGeneral: '4,000-11,000' },
          { parameter: 'RBC Count', unit: 'million/μL', normalRangeMale: '4.5-5.5', normalRangeFemale: '4.0-5.0' },
          { parameter: 'Platelet Count', unit: 'cells/μL', normalRangeGeneral: '150,000-400,000' },
          { parameter: 'Hematocrit', unit: '%', normalRangeMale: '40-54', normalRangeFemale: '36-48' },
          { parameter: 'MCV', unit: 'fL', normalRangeGeneral: '80-100' },
          { parameter: 'MCH', unit: 'pg', normalRangeGeneral: '27-33' },
          { parameter: 'MCHC', unit: 'g/dL', normalRangeGeneral: '32-36' },
        ],
      },
      {
        code: 'MP',
        name: 'Malaria Parasite Test',
        price: 5000,
        turnaroundTime: '30 mins',
        sampleType: 'Blood (EDTA)',
        containerType: 'Purple top tube',
        parameters: [
          { parameter: 'Malaria Parasite', unit: '', normalRangeGeneral: 'Negative' },
        ],
      },
      {
        code: 'BGRH',
        name: 'Blood Group & Rh Factor',
        price: 8000,
        turnaroundTime: '1 hour',
        sampleType: 'Blood (EDTA)',
        containerType: 'Purple top tube',
        parameters: [
          { parameter: 'Blood Group', unit: '', normalRangeGeneral: 'A/B/AB/O' },
          { parameter: 'Rh Factor', unit: '', normalRangeGeneral: 'Positive/Negative' },
        ],
      },
      {
        code: 'ESR',
        name: 'ESR (Erythrocyte Sedimentation Rate)',
        price: 7000,
        turnaroundTime: '1 hour',
        sampleType: 'Blood (EDTA)',
        containerType: 'Purple top tube',
        parameters: [
          { parameter: 'ESR', unit: 'mm/hr', normalRangeMale: '0-15', normalRangeFemale: '0-20' },
        ],
      },
      {
        code: 'RETIC',
        name: 'Reticulocyte Count',
        price: 12000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (EDTA)',
        containerType: 'Purple top tube',
        parameters: [
          { parameter: 'Reticulocyte Count', unit: '%', normalRangeGeneral: '0.5-2.5' },
        ],
      },
    ],
  },
  {
    name: 'BIOCHEMISTRY',
    description: 'Chemical analysis of blood and body fluids',
    tests: [
      {
        code: 'LFT',
        name: 'Liver Function Tests',
        price: 25000,
        turnaroundTime: '4 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'Total Bilirubin', unit: 'mg/dL', normalRangeGeneral: '0.3-1.2' },
          { parameter: 'Direct Bilirubin', unit: 'mg/dL', normalRangeGeneral: '0.0-0.3' },
          { parameter: 'AST (SGOT)', unit: 'U/L', normalRangeGeneral: '10-40' },
          { parameter: 'ALT (SGPT)', unit: 'U/L', normalRangeGeneral: '7-56' },
          { parameter: 'ALP', unit: 'U/L', normalRangeGeneral: '44-147' },
          { parameter: 'Total Protein', unit: 'g/dL', normalRangeGeneral: '6.0-8.3' },
          { parameter: 'Albumin', unit: 'g/dL', normalRangeGeneral: '3.5-5.5' },
        ],
      },
      {
        code: 'RFT',
        name: 'Renal Function Tests',
        price: 20000,
        turnaroundTime: '4 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'Urea', unit: 'mg/dL', normalRangeGeneral: '15-45' },
          { parameter: 'Creatinine', unit: 'mg/dL', normalRangeMale: '0.7-1.3', normalRangeFemale: '0.6-1.1' },
          { parameter: 'Uric Acid', unit: 'mg/dL', normalRangeMale: '3.5-7.2', normalRangeFemale: '2.6-6.0' },
          { parameter: 'Sodium', unit: 'mmol/L', normalRangeGeneral: '136-145' },
          { parameter: 'Potassium', unit: 'mmol/L', normalRangeGeneral: '3.5-5.1' },
          { parameter: 'Chloride', unit: 'mmol/L', normalRangeGeneral: '98-107' },
        ],
      },
      {
        code: 'GLUC',
        name: 'Blood Glucose',
        price: 8000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (Fluoride)',
        containerType: 'Grey top tube',
        parameters: [
          { parameter: 'Glucose (Fasting)', unit: 'mg/dL', normalRangeGeneral: '70-100' },
          { parameter: 'Glucose (Random)', unit: 'mg/dL', normalRangeGeneral: '70-140' },
        ],
      },
      {
        code: 'LIPID',
        name: 'Lipid Profile',
        price: 30000,
        turnaroundTime: '4 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'Total Cholesterol', unit: 'mg/dL', normalRangeGeneral: '<200' },
          { parameter: 'HDL Cholesterol', unit: 'mg/dL', normalRangeGeneral: '>40' },
          { parameter: 'LDL Cholesterol', unit: 'mg/dL', normalRangeGeneral: '<100' },
          { parameter: 'Triglycerides', unit: 'mg/dL', normalRangeGeneral: '<150' },
        ],
      },
      {
        code: 'HBA1C',
        name: 'HbA1c (Glycated Hemoglobin)',
        price: 25000,
        turnaroundTime: '24 hours',
        sampleType: 'Blood (EDTA)',
        containerType: 'Purple top tube',
        parameters: [
          { parameter: 'HbA1c', unit: '%', normalRangeGeneral: '4.0-5.6' },
        ],
      },
    ],
  },
  {
    name: 'MICROBIOLOGY',
    description: 'Bacterial and fungal culture tests',
    tests: [
      {
        code: 'C&S',
        name: 'Culture & Sensitivity',
        price: 35000,
        turnaroundTime: '48-72 hours',
        sampleType: 'Various',
        containerType: 'Sterile container',
        parameters: [
          { parameter: 'Culture Result', unit: '', normalRangeGeneral: 'No Growth' },
          { parameter: 'Sensitivity', unit: '', normalRangeGeneral: 'N/A' },
        ],
      },
      {
        code: 'GXP',
        name: 'TB GeneXpert',
        price: 55000,
        turnaroundTime: '2 hours',
        sampleType: 'Sputum',
        containerType: 'Sputum container',
        parameters: [
          { parameter: 'MTB Detection', unit: '', normalRangeGeneral: 'Not Detected' },
          { parameter: 'Rifampicin Resistance', unit: '', normalRangeGeneral: 'N/A' },
        ],
      },
      {
        code: 'STOOL',
        name: 'Stool Microscopy',
        price: 10000,
        turnaroundTime: '2 hours',
        sampleType: 'Stool',
        containerType: 'Stool container',
        parameters: [
          { parameter: 'Consistency', unit: '', normalRangeGeneral: 'Formed' },
          { parameter: 'Ova/Parasites', unit: '', normalRangeGeneral: 'None Seen' },
          { parameter: 'Pus Cells', unit: '/HPF', normalRangeGeneral: 'Nil' },
          { parameter: 'RBC', unit: '/HPF', normalRangeGeneral: 'Nil' },
        ],
      },
      {
        code: 'URINE',
        name: 'Urine Microscopy',
        price: 10000,
        turnaroundTime: '2 hours',
        sampleType: 'Urine',
        containerType: 'Urine container',
        parameters: [
          { parameter: 'Appearance', unit: '', normalRangeGeneral: 'Clear' },
          { parameter: 'pH', unit: '', normalRangeGeneral: '4.5-8.0' },
          { parameter: 'Protein', unit: '', normalRangeGeneral: 'Negative' },
          { parameter: 'Glucose', unit: '', normalRangeGeneral: 'Negative' },
          { parameter: 'Pus Cells', unit: '/HPF', normalRangeGeneral: '0-5' },
          { parameter: 'RBC', unit: '/HPF', normalRangeGeneral: '0-3' },
          { parameter: 'Epithelial Cells', unit: '/HPF', normalRangeGeneral: 'Few' },
          { parameter: 'Bacteria', unit: '', normalRangeGeneral: 'None Seen' },
        ],
      },
      {
        code: 'GRAM',
        name: 'Gram Stain',
        price: 12000,
        turnaroundTime: '2 hours',
        sampleType: 'Various',
        containerType: 'Sterile container',
        parameters: [
          { parameter: 'Gram Stain Result', unit: '', normalRangeGeneral: 'No Organisms Seen' },
        ],
      },
    ],
  },
  {
    name: 'SEROLOGY',
    description: 'Antibody and antigen detection tests',
    tests: [
      {
        code: 'HIV',
        name: 'HIV Rapid Test',
        price: 10000,
        turnaroundTime: '30 mins',
        sampleType: 'Blood',
        containerType: 'EDTA tube',
        parameters: [
          { parameter: 'HIV Test', unit: '', normalRangeGeneral: 'Non-Reactive' },
        ],
      },
      {
        code: 'HBSAG',
        name: 'Hepatitis B Surface Antigen',
        price: 15000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'HBsAg', unit: '', normalRangeGeneral: 'Negative' },
        ],
      },
      {
        code: 'HCV',
        name: 'Hepatitis C Antibody',
        price: 20000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'HCV Antibody', unit: '', normalRangeGeneral: 'Negative' },
        ],
      },
      {
        code: 'RPR',
        name: 'Syphilis (RPR)',
        price: 12000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'RPR', unit: '', normalRangeGeneral: 'Non-Reactive' },
        ],
      },
      {
        code: 'COVID',
        name: 'COVID-19 Antigen Test',
        price: 45000,
        turnaroundTime: '30 mins',
        sampleType: 'Nasopharyngeal Swab',
        containerType: 'Swab kit',
        parameters: [
          { parameter: 'COVID-19 Antigen', unit: '', normalRangeGeneral: 'Negative' },
        ],
      },
    ],
  },
  {
    name: 'HORMONES',
    description: 'Hormone level tests',
    tests: [
      {
        code: 'TFT',
        name: 'Thyroid Function Tests',
        price: 45000,
        turnaroundTime: '24 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'TSH', unit: 'mIU/L', normalRangeGeneral: '0.4-4.0' },
          { parameter: 'Free T4', unit: 'ng/dL', normalRangeGeneral: '0.8-1.8' },
          { parameter: 'Free T3', unit: 'pg/mL', normalRangeGeneral: '2.3-4.2' },
        ],
      },
      {
        code: 'PSA',
        name: 'PSA Total',
        price: 35000,
        turnaroundTime: '24 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'PSA Total', unit: 'ng/mL', normalRangeGeneral: '0.0-4.0' },
        ],
      },
      {
        code: 'BHCG',
        name: 'Beta HCG (Pregnancy Test)',
        price: 25000,
        turnaroundTime: '2 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'Beta HCG', unit: 'mIU/mL', normalRangeGeneral: '<5 (Non-Pregnant)' },
        ],
      },
      {
        code: 'PROG',
        name: 'Progesterone',
        price: 30000,
        turnaroundTime: '24 hours',
        sampleType: 'Blood (Serum)',
        containerType: 'Red top tube',
        parameters: [
          { parameter: 'Progesterone', unit: 'ng/mL', normalRangeFemale: '0.1-0.7 (Follicular), 2-25 (Luteal)' },
        ],
      },
    ],
  },
];

// Uganda Districts
export const UGANDA_DISTRICTS = [
  'Kampala', 'Wakiso', 'Mukono', 'Mpigi', 'Luwero', 'Nakasongola', 'Kayunga',
  'Mbarara', 'Ntungamo', 'Bushenyi', 'Rukungiri', 'Kabale', 'Kanungu',
  'Masaka', 'Rakai', 'Lyantonde', 'Lwengo', 'Sembabule',
  'Jinja', 'Iganga', 'Kamuli', 'Bugiri', 'Mayuge', 'Namutumba',
  'Mbale', 'Tororo', 'Busia', 'Bududa', 'Manafwa', 'Sironko',
  'Gulu', 'Kitgum', 'Pader', 'Amuru', 'Nwoya', 'Lamwo',
  'Lira', 'Apac', 'Oyam', 'Kole', 'Dokolo', 'Amolatar',
  'Moroto', 'Kotido', 'Kaabong', 'Abim', 'Napak', 'Amudat',
  'Hoima', 'Masindi', 'Kibaale', 'Buliisa', 'Kiryandongo',
  'Fort Portal', 'Kasese', 'Bundibugyo', 'Ntoroko', 'Kamwenge',
  'Mubende', 'Mityana', 'Kiboga', 'Kyankwanzi',
  'Arua', 'Nebbi', 'Yumbe', 'Moyo', 'Adjumani', 'Koboko', 'Maracha',
  'Soroti', 'Kumi', 'Kaberamaido', 'Katakwi', 'Amuria', 'Ngora', 'Serere',
];
