import { TestCategory, Test, NormalRange } from './types';

export const testCategories: TestCategory[] = [
  {
    id: 'hematology',
    name: 'HEMATOLOGY',
    description: 'Blood and blood-forming organs tests',
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'biochemistry',
    name: 'BIOCHEMISTRY',
    description: 'Chemical analysis of body fluids',
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'microbiology',
    name: 'MICROBIOLOGY',
    description: 'Microorganism identification and testing',
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'serology',
    name: 'SEROLOGY',
    description: 'Antibody and antigen testing',
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'hormones',
    name: 'HORMONES',
    description: 'Endocrine system hormone testing',
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'urinalysis',
    name: 'URINALYSIS',
    description: 'Urine analysis and testing',
    isActive: true,
    createdAt: new Date(),
  },
];

export const normalRanges: { [key: string]: NormalRange[] } = {
  hemoglobin: [
    {
      id: 'hb-male',
      parameter: 'Hemoglobin',
      unit: 'g/dL',
      minValue: 13.0,
      maxValue: 17.0,
      gender: 'Male',
      flag: 'Normal',
    },
    {
      id: 'hb-female',
      parameter: 'Hemoglobin',
      unit: 'g/dL',
      minValue: 12.0,
      maxValue: 15.0,
      gender: 'Female',
      flag: 'Normal',
    },
  ],
  malaria: [
    {
      id: 'mp-normal',
      parameter: 'Malaria Parasite',
      unit: '',
      normalValue: 'Negative',
      gender: 'Both',
      flag: 'Normal',
    },
  ],
  bloodGlucose: [
    {
      id: 'glucose-fasting',
      parameter: 'Blood Glucose (Fasting)',
      unit: 'mg/dL',
      minValue: 70,
      maxValue: 100,
      gender: 'Both',
      flag: 'Normal',
    },
    {
      id: 'glucose-random',
      parameter: 'Blood Glucose (Random)',
      unit: 'mg/dL',
      minValue: 70,
      maxValue: 140,
      gender: 'Both',
      flag: 'Normal',
    },
  ],
  wbc: [
    {
      id: 'wbc-adult',
      parameter: 'White Blood Cell Count',
      unit: 'cells/μL',
      minValue: 4000,
      maxValue: 11000,
      gender: 'Both',
      flag: 'Normal',
    },
  ],
  hiv: [
    {
      id: 'hiv-negative',
      parameter: 'HIV Rapid Test',
      unit: '',
      normalValue: 'Negative',
      gender: 'Both',
      flag: 'Normal',
    },
  ],
};

export const tests: Test[] = [
  // HEMATOLOGY
  {
    id: 'fbc',
    categoryId: 'hematology',
    name: 'Full Hemogram',
    code: 'FBC',
    price: 15000,
    turnaroundTime: '2 hours',
    sampleType: 'Blood',
    containerType: 'EDTA Tube',
    storageRequirements: 'Room temperature',
    normalRanges: [
      ...normalRanges.hemoglobin,
      ...normalRanges.wbc,
      {
        id: 'rbc',
        parameter: 'Red Blood Cell Count',
        unit: 'million/μL',
        minValue: 4.5,
        maxValue: 5.5,
        gender: 'Male',
        flag: 'Normal',
      },
      {
        id: 'rbc-female',
        parameter: 'Red Blood Cell Count',
        unit: 'million/μL',
        minValue: 4.0,
        maxValue: 5.0,
        gender: 'Female',
        flag: 'Normal',
      },
      {
        id: 'platelets',
        parameter: 'Platelet Count',
        unit: 'thousand/μL',
        minValue: 150,
        maxValue: 450,
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'mp',
    categoryId: 'hematology',
    name: 'Malaria Parasite Test',
    code: 'MP',
    price: 5000,
    turnaroundTime: '30 mins',
    sampleType: 'Blood',
    containerType: 'EDTA Tube',
    storageRequirements: 'Room temperature',
    normalRanges: normalRanges.malaria,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'bgrh',
    categoryId: 'hematology',
    name: 'Blood Group & Rh Factor',
    code: 'BGRH',
    price: 8000,
    turnaroundTime: '1 hour',
    sampleType: 'Blood',
    containerType: 'EDTA Tube',
    storageRequirements: 'Room temperature',
    normalRanges: [
      {
        id: 'blood-group',
        parameter: 'Blood Group',
        unit: '',
        normalValue: 'A, B, AB, or O',
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 'rh-factor',
        parameter: 'Rh Factor',
        unit: '',
        normalValue: 'Positive or Negative',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'esr',
    categoryId: 'hematology',
    name: 'ESR',
    code: 'ESR',
    price: 7000,
    turnaroundTime: '1 hour',
    sampleType: 'Blood',
    containerType: 'EDTA Tube',
    storageRequirements: 'Room temperature',
    normalRanges: [
      {
        id: 'esr-male',
        parameter: 'ESR',
        unit: 'mm/hr',
        minValue: 0,
        maxValue: 15,
        gender: 'Male',
        flag: 'Normal',
      },
      {
        id: 'esr-female',
        parameter: 'ESR',
        unit: 'mm/hr',
        minValue: 0,
        maxValue: 20,
        gender: 'Female',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },

  // BIOCHEMISTRY
  {
    id: 'lft',
    categoryId: 'biochemistry',
    name: 'Liver Function Tests',
    code: 'LFT',
    price: 25000,
    turnaroundTime: '4 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'alt',
        parameter: 'ALT',
        unit: 'U/L',
        minValue: 7,
        maxValue: 56,
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 'ast',
        parameter: 'AST',
        unit: 'U/L',
        minValue: 10,
        maxValue: 40,
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 'bilirubin-total',
        parameter: 'Total Bilirubin',
        unit: 'mg/dL',
        minValue: 0.3,
        maxValue: 1.2,
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'rft',
    categoryId: 'biochemistry',
    name: 'Renal Function Tests',
    code: 'RFT',
    price: 20000,
    turnaroundTime: '4 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'urea',
        parameter: 'Urea',
        unit: 'mg/dL',
        minValue: 7,
        maxValue: 20,
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 'creatinine',
        parameter: 'Creatinine',
        unit: 'mg/dL',
        minValue: 0.6,
        maxValue: 1.2,
        gender: 'Male',
        flag: 'Normal',
      },
      {
        id: 'creatinine-female',
        parameter: 'Creatinine',
        unit: 'mg/dL',
        minValue: 0.5,
        maxValue: 1.1,
        gender: 'Female',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'glucose',
    categoryId: 'biochemistry',
    name: 'Blood Glucose',
    code: 'GLUC',
    price: 8000,
    turnaroundTime: '2 hours',
    sampleType: 'Blood',
    containerType: 'Fluoride Tube',
    storageRequirements: 'Room temperature',
    normalRanges: normalRanges.bloodGlucose,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'lipid',
    categoryId: 'biochemistry',
    name: 'Lipid Profile',
    code: 'LIPID',
    price: 30000,
    turnaroundTime: '4 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'cholesterol',
        parameter: 'Total Cholesterol',
        unit: 'mg/dL',
        minValue: 0,
        maxValue: 200,
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 'hdl',
        parameter: 'HDL Cholesterol',
        unit: 'mg/dL',
        minValue: 40,
        maxValue: 999,
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 'ldl',
        parameter: 'LDL Cholesterol',
        unit: 'mg/dL',
        minValue: 0,
        maxValue: 100,
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },

  // MICROBIOLOGY
  {
    id: 'cs',
    categoryId: 'microbiology',
    name: 'Culture & Sensitivity',
    code: 'C&S',
    price: 35000,
    turnaroundTime: '48-72 hours',
    sampleType: 'Other',
    containerType: 'Sterile Container',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'culture',
        parameter: 'Culture Result',
        unit: '',
        normalValue: 'No growth',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'tb-gxp',
    categoryId: 'microbiology',
    name: 'TB GeneXpert',
    code: 'GXP',
    price: 55000,
    turnaroundTime: '2 hours',
    sampleType: 'Sputum',
    containerType: 'Sputum Container',
    storageRequirements: 'Room temperature',
    normalRanges: [
      {
        id: 'tb-gxp',
        parameter: 'TB GeneXpert',
        unit: '',
        normalValue: 'Not Detected',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'stool',
    categoryId: 'microbiology',
    name: 'Stool Microscopy',
    code: 'STOOL',
    price: 10000,
    turnaroundTime: '2 hours',
    sampleType: 'Stool',
    containerType: 'Stool Container',
    storageRequirements: 'Room temperature',
    normalRanges: [
      {
        id: 'stool-ova',
        parameter: 'Ova and Parasites',
        unit: '',
        normalValue: 'Not seen',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },

  // SEROLOGY
  {
    id: 'hiv',
    categoryId: 'serology',
    name: 'HIV Rapid Test',
    code: 'HIV',
    price: 10000,
    turnaroundTime: '30 mins',
    sampleType: 'Blood',
    containerType: 'EDTA Tube',
    storageRequirements: 'Room temperature',
    normalRanges: normalRanges.hiv,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'hbsag',
    categoryId: 'serology',
    name: 'Hepatitis B Surface Antigen',
    code: 'HBSAG',
    price: 15000,
    turnaroundTime: '2 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'hbsag',
        parameter: 'HBsAg',
        unit: '',
        normalValue: 'Negative',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'hcv',
    categoryId: 'serology',
    name: 'Hepatitis C Antibody',
    code: 'HCV',
    price: 20000,
    turnaroundTime: '2 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'hcv',
        parameter: 'HCV Antibody',
        unit: '',
        normalValue: 'Negative',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'covid',
    categoryId: 'serology',
    name: 'COVID-19 Antigen Test',
    code: 'COVID',
    price: 45000,
    turnaroundTime: '30 mins',
    sampleType: 'Other',
    containerType: 'Nasal Swab',
    storageRequirements: 'Room temperature',
    normalRanges: [
      {
        id: 'covid',
        parameter: 'COVID-19 Antigen',
        unit: '',
        normalValue: 'Negative',
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },

  // HORMONES
  {
    id: 'tft',
    categoryId: 'hormones',
    name: 'Thyroid Function Tests',
    code: 'TFT',
    price: 45000,
    turnaroundTime: '24 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'tsh',
        parameter: 'TSH',
        unit: 'mIU/L',
        minValue: 0.4,
        maxValue: 4.0,
        gender: 'Both',
        flag: 'Normal',
      },
      {
        id: 't4',
        parameter: 'Free T4',
        unit: 'ng/dL',
        minValue: 0.8,
        maxValue: 1.8,
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'psa',
    categoryId: 'hormones',
    name: 'PSA Total',
    code: 'PSA',
    price: 35000,
    turnaroundTime: '24 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'psa',
        parameter: 'PSA Total',
        unit: 'ng/mL',
        minValue: 0,
        maxValue: 4.0,
        gender: 'Male',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'bhcg',
    categoryId: 'hormones',
    name: 'Beta HCG',
    code: 'BHCG',
    price: 25000,
    turnaroundTime: '2 hours',
    sampleType: 'Blood',
    containerType: 'Serum Separator Tube',
    storageRequirements: 'Refrigerated',
    normalRanges: [
      {
        id: 'bhcg-negative',
        parameter: 'Beta HCG',
        unit: 'mIU/mL',
        minValue: 0,
        maxValue: 5,
        gender: 'Both',
        flag: 'Normal',
      },
    ],
    isActive: true,
    createdAt: new Date(),
  },
];